# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnnavbars',
            options={'managed': True, 'ordering': ['sort_no'], 'verbose_name': 'العنوان الفرعي في رأس الصفحة', 'verbose_name_plural': 'العنوان الفرعي في رأس الصفحة'},
        ),
        migrations.AlterModelOptions(
            name='navbars',
            options={'managed': True, 'ordering': ['sort_no'], 'verbose_name': 'العنوان في رأس الصفحة', 'verbose_name_plural': 'العنوان في رأس الصفحة'},
        ),
        migrations.AlterField(
            model_name='columnnavbars',
            name='titel',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='اسم القسم'),
        ),
    ]
