# Generated by Django 3.2.22 on 2023-11-09 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teams.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='الأسم الكامل')),
                ('jop', models.CharField(max_length=250, null=True, verbose_name='العمل')),
                ('facebook', models.URLField(blank=True, help_text='https://facebook.com', null=True, validators=[teams.models.validate_hostname], verbose_name='رابط حساب الفيسبوك إن وجد ')),
                ('twitter', models.URLField(blank=True, help_text='https://twitter.com', null=True, validators=[teams.models.validate_hostname], verbose_name='رابط حساب تويتر او منصة اكس إن وجد ')),
                ('instagram', models.URLField(blank=True, help_text='https://instagram.com', null=True, validators=[teams.models.validate_hostname], verbose_name='رابط حساب انستجرام إن وجد ')),
                ('linkedin', models.URLField(blank=True, help_text='https://linkedin.com', null=True, validators=[teams.models.validate_hostname], verbose_name='رابط حساب لنكدإن  إن وجد ')),
                ('youtube', models.URLField(blank=True, help_text='https://youtube.com', null=True, validators=[teams.models.validate_hostname], verbose_name='رابط قناة اليوتيوب ')),
                ('detial_ar', tinymce.models.HTMLField(blank=True, default=' ', max_length=100000, null=True, verbose_name='كلمة إن وجد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image/Teams/%Y/%m/%d/', verbose_name=' إختيار صورة')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الحذف ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأنشاء ')),
                ('edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ اخر تعديل ')),
                ('is_hidden', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا من العرض بالموقع بحال تم تحديده', verbose_name='مخفي')),
                ('is_deleted', models.BooleanField(default=False, help_text='سيتم اخفاء هذا من العرض بالموقع بحال تم تحديده وسيعتبر انه قد تم حذفه  ', verbose_name='محذوف ')),
                ('sort_no', models.IntegerField(blank=True, null=True, verbose_name='رقم الترتيب (يرتب بالموقع حسب الرقم)')),
                ('short_note', models.CharField(blank=True, default=' ', help_text=' اختياري - فقط لأجل ان وجد لديكم اي ملاحظة للعمل عليها مستقبلاً', max_length=200, null=True, verbose_name='ملاحظة قصيرة إن وجد')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الأنشاء بواسطة ')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم الحذف  بواسطة ')),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_edited_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم التعديل  بواسطة ')),
            ],
            options={
                'verbose_name': 'فريق العمل',
                'verbose_name_plural': 'فريق العمل',
                'managed': True,
            },
        ),
    ]
