# Generated by Django 3.2.22 on 2023-11-30 19:50

import branches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0018_auto_20231122_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesservices',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Service Type Name'),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='app_store',
            field=models.URLField(blank=True, help_text='https://apps.apple.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق على اب استور '),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='desketop',
            field=models.URLField(blank=True, help_text='https://play.google.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق تحميل desketop'),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='google_play',
            field=models.URLField(blank=True, help_text='https://play.google.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق على جوجل ابلاي '),
        ),
        migrations.AlterField(
            model_name='categoriesservices',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='اسم نوع الخدمة'),
        ),
    ]
