# Generated by Django 3.2.22 on 2023-12-03 19:42

import branches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0020_auto_20231130_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankapplications',
            name='detial_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='اسم التطبيق انجليزي'),
        ),
        migrations.AddField(
            model_name='bankapplications',
            name='titel_en',
            field=models.CharField(default='', max_length=50, verbose_name='اسم التطبيق انجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futureapplications',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='اسم الميزة انجليزي'),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='app_store',
            field=models.URLField(blank=True, help_text='https://apps.apple.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق على اب استور '),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='desketop',
            field=models.URLField(blank=True, help_text='https://play.google.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق تحميل desketop'),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='google_play',
            field=models.URLField(blank=True, help_text='https://play.google.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق على جوجل ابلاي '),
        ),
    ]
