# Generated by Django 3.2.22 on 2023-12-16 17:48

import branches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0046_auto_20231216_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankapplications',
            name='app_store',
            field=models.URLField(blank=True, help_text='https://apps.apple.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق على اب استور '),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='desketop',
            field=models.URLField(blank=True, help_text='https://play.google.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق تحميل desketop'),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='google_play',
            field=models.URLField(blank=True, help_text='https://play.google.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق على جوجل ابلاي '),
        ),
        migrations.AlterField(
            model_name='services',
            name='detial_ar',
            field=models.TextField(default=' ', max_length=100000, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='services',
            name='detial_en',
            field=models.TextField(default=' ', max_length=100000, null=True, verbose_name='التفاصيل بالانجليزي'),
        ),
    ]
