# Generated by Django 4.2.7 on 2024-01-06 10:49

import branches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0048_auto_20231217_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description_ar',
            field=models.TextField(default=' ', max_length=100000, null=True, verbose_name='وصف مختصر للخدمة عربي'),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(default=' ', max_length=100000, null=True, verbose_name='وصف مختصر للخدمة انجليزي'),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='app_store',
            field=models.URLField(blank=True, help_text='https://apps.apple.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق على اب استور '),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='desketop',
            field=models.URLField(blank=True, help_text='https://play.google.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق تحميل desketop'),
        ),
        migrations.AlterField(
            model_name='bankapplications',
            name='google_play',
            field=models.URLField(blank=True, help_text='https://play.google.com', null=True, validators=[branches.models.validate_hostname], verbose_name='رابط تطبيق على جوجل ابلاي '),
        ),
    ]
