# Generated by Django 4.0 on 2023-05-06 07:17

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMarch',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Detial_AR', tinymce.models.HTMLField(blank=True, default=' ',
                 max_length=10000000, null=True, verbose_name='تفاصيل رؤية الشركة')),
                ('Date_Update', models.DateTimeField(
                    auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(
                    auto_now_add=True, verbose_name='تاريخ الأضافة ')),
                ('is_hidden', models.BooleanField(default=False,
                 help_text=' سيتم اخفاء هذا  من العرض بالموقع بحال تم تحديده', verbose_name='مخفي')),
                ('is_deleted', models.BooleanField(default=False,
                 help_text='سيتم اخفاء هذا الرئي من العرض بالموقع بحال تم تحديده وسيعتبر انه قد تم حذفه  ', verbose_name='محذوف ')),
                ('deleted_at', models.DateTimeField(
                    blank=True, editable=False, null=True)),
                ('sort_no', models.IntegerField(
                    blank=True, help_text=' اختياري - يتم ترتيب ظهور الأراء على حسب الرقم هذا ان وجد', null=True, verbose_name='رقم الترتيب ')),
                ('short_note', models.CharField(blank=True, default=' ', help_text=' اختياري - فقط لأجل ان وجد لديكم اي ملاحظة للعمل عليها مستقبلاً',
                 max_length=1000, null=True, verbose_name='ملاحظة قصيرة')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='تم الأنشاء بواسطة ')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='OurMarch_deleted_by', to='auth.user')),
            ],
            options={
                'verbose_name': 'مسيرتنــــا',
                'verbose_name_plural': 'مسيرتنــــا',
                'managed': True,
            },
        ),
    ]
