# Generated by Django 4.0 on 2023-05-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('OurMarch', '0002_remove_ourmarch_sort_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmarch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأنشاء '),
        ),
        migrations.AddField(
            model_name='ourmarch',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ اخر تعديل '),
        ),
        migrations.AddField(
            model_name='ourmarch',
            name='edited_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OurMarch_edited_by', to='auth.user', verbose_name=' تم التعديل  بواسطة '),
        ),
        migrations.AlterField(
            model_name='ourmarch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الحذف '),
        ),
        migrations.AlterField(
            model_name='ourmarch',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OurMarch_deleted_by', to='auth.user', verbose_name=' تم الحذف  بواسطة '),
        ),
    ]
