# Generated by Django 4.2.5 on 2023-09-10 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("OurMarch", "0003_ourmarch_created_at_ourmarch_edited_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ourmarch",
            old_name="Detial_AR",
            new_name="detial_ar",
        ),
    ]
