# Generated by Django 4.2.5 on 2023-09-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OurMarch", "0004_rename_detial_ar_ourmarch_detial_ar"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourmarch",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="Image/OurMarch/%Y/%m/%d/",
                verbose_name=" إختيار صورة",
            ),
        ),
    ]
