# Generated by Django 3.2.22 on 2023-12-04 06:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('OurMarch', '0005_ourmarch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmarch',
            name='detial_en',
            field=tinymce.models.HTMLField(blank=True, default=' ', max_length=10000000, null=True, verbose_name='تفاصيل رؤية الشركة بالانجليزي'),
        ),
    ]
