# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'managed': True, 'verbose_name': 'المقالات و آخر الأخبار', 'verbose_name_plural': 'المقالات و آخر الأخبار'},
        ),
        migrations.AlterModelOptions(
            name='categoryblog',
            options={'managed': True, 'verbose_name': 'قسم المقالات و آخر الأخبار', 'verbose_name_plural': 'قسم المقالات و آخر الأخبار'},
        ),
        migrations.AlterModelOptions(
            name='policies',
            options={'managed': True, 'verbose_name': 'السياسات', 'verbose_name_plural': 'السياسات'},
        ),
    ]
