# Generated by Django 3.2.22 on 2023-12-04 12:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20231203_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='detial_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='المقال او المحتوى بالانجليزي'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='titel_en',
            field=models.CharField(default='', max_length=70, verbose_name='عنوان الخبر او المقالة بالانجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryblog',
            name='name_en',
            field=models.CharField(default='', max_length=250, verbose_name='عنوان القسم بالانجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policies',
            name='detial_en',
            field=tinymce.models.HTMLField(default='', max_length=1000000000, null=True, verbose_name='تفاصيل بالانجليزي'),
        ),
        migrations.AddField(
            model_name='policies',
            name='titel_en',
            field=models.CharField(default='', max_length=70, verbose_name='عنوان السياسة بالانجليزي'),
            preserve_default=False,
        ),
    ]
