# Generated by Django 3.2.22 on 2023-11-09 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name=' status ')),
                ('cookie', tinymce.models.HTMLField(blank=True, default=' ', editable=False, max_length=100000, null=True)),
                ('COOKIES', tinymce.models.HTMLField(blank=True, default=' ', editable=False, max_length=100000, null=True)),
                ('ip', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name=' Ip')),
                ('country', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name=' الدولة')),
                ('screen', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name=' الشاشة ')),
                ('countryCode', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name=' رمز الدولة')),
                ('timezone', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='timezone')),
                ('city', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name=' المدينة ')),
                ('regionCode', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name=' رمز المنطقة ')),
                ('regionName', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name=' اسم المنطقة ')),
                ('isp', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name=' مزود خدمة الإنترنت ISP  Internet service provider ')),
                ('org', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name=' منظمة org ')),
                ('asn', models.CharField(blank=True, default='', editable=False, max_length=200, null=True, verbose_name=' أرقام النظام الذاتي Autonomous System Numbers ')),
                ('zip', models.CharField(blank=True, default='', editable=False, max_length=20, null=True, verbose_name=' أرقام النظام الذاتي Autonomous System Numbers ')),
                ('latitude', models.FloatField(blank=True, editable=False, null=True, verbose_name=' latitude خط العرض')),
                ('longitude', models.FloatField(blank=True, editable=False, null=True, verbose_name=' longitude خط الطول')),
                ('url_google_map_location', models.URLField(blank=True, default='https://www.google.com/maps?q=15.3538569,44.2058841', editable=False, null=True, verbose_name=' رابط الموقع النقريبي للمستخدم على خرائط جوجل ')),
                ('security_is_bogon', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name=' security is bogon ')),
                ('security_is_cloud_provider', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='الأمن هو مزود السحابة security is cloud provider ')),
                ('security_is_tor_exit', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='security is tor exit')),
                ('security_is_tor', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='  security is tor')),
                ('security_is_proxy', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name=' security_is_proxy ')),
                ('security_is_abuser', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name=' security_is_abuser امان الشبكة مسيء')),
                ('security_is_anonymous', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='الشبكة مجهولة ')),
                ('security_is_attacker', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name=' مهاجم')),
                ('security_is_threat', models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='تهديد ')),
                ('IMEI_device', models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name=' معرف الجهاز')),
                ('Date_Update', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأضافة ')),
            ],
            options={
                'verbose_name': 'معلومات IP',
                'verbose_name_plural': 'معلومات IP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='الرقم')),
                ('titel', models.CharField(max_length=20, null=True, verbose_name='العنوان')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الأنشاء بواسطة ')),
            ],
            options={
                'verbose_name': 'نقاط تواجدنا',
                'verbose_name_plural': 'نقاط تواجدنا',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestMetaAndGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datajson', models.JSONField()),
                ('datajsonGet', models.JSONField(blank=True, null=True)),
                ('cookie', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('Date_Update', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأضافة ')),
                ('CONTENT_LENGTH', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('CONTENT_TYPE', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('HTTP_ACCEPT', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('HTTP_ACCEPT_ENCODING', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('HTTP_ACCEPT_LANGUAGE', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('HTTP_HOST', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('HTTP_REFERER', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('HTTP_USER_AGENT', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('QUERY_STRING', tinymce.models.HTMLField(default=' ', max_length=100000, null=True, verbose_name='QUERY_STRING ')),
                ('REMOTE_ADDR', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('REMOTE_HOST', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('REMOTE_USER', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('REQUEST_METHOD', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('SERVER_NAME', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('SERVER_PORT', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('GET', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('encoding', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('COOKIES', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('PATH', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('ip_info', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anmaabankApp.ipinfo')),
            ],
            options={
                'verbose_name': 'معلومات ريكوست الميتا',
                'verbose_name_plural': 'معلومات ريكوست الميتا',
                'ordering': ('Date_Update',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestHederInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datajson', models.JSONField()),
                ('Date_Update', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأضافة ')),
                ('latitude', models.FloatField(default=0.0, null=True, verbose_name=' latitude خط العرض')),
                ('longitude', models.FloatField(default=0.0, null=True, verbose_name=' longitude خط الطول')),
                ('cookie', tinymce.models.HTMLField(default=' ', max_length=100000, null=True)),
                ('ip_info', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anmaabankApp.ipinfo')),
            ],
            options={
                'verbose_name': 'معلومات ريكوست الهيدر',
                'verbose_name_plural': 'معلومات ريكوست الهيدر',
                'ordering': ('Date_Update',),
                'managed': True,
            },
        ),
    ]
