# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmaabankApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipinfo',
            name='status',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='status'),
        ),
    ]
