# Generated by Django 3.2.22 on 2023-11-30 19:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttoopenaccount',
            name='Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='رقم التلفون'),
        ),
        migrations.AlterField(
            model_name='requesttoopenaccount',
            name='emile',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الألكتروني'),
        ),
    ]
