# Generated by Django 4.2.7 on 2024-01-06 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_regions', '0001_initial'),
        ('jopapp', '0002_auto_20231130_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdata',
            name='region',
            field=models.ForeignKey(help_text='اختار المحافظة', null=True, on_delete=django.db.models.deletion.SET_NULL, to='country_regions.region', verbose_name='المحافظة'),
        ),
    ]
