# Generated by Django 4.2.7 on 2024-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jopapp', '0003_alter_birthdata_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
