# Generated by Django 4.2.7 on 2024-01-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jopapp', '0004_alter_education_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
