# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'managed': True, 'verbose_name': 'الشركاء', 'verbose_name_plural': 'الشركاء'},
        ),
    ]
