# Generated by Django 3.2.22 on 2023-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partners', '0002_alter_partners_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='full_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
