# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='image',
            field=models.ImageField(null=True, upload_to='Image/OurVision/%Y/%m/%d/', verbose_name='إختيار صورة'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='short_note',
            field=models.CharField(blank=True, default=' ', help_text='اختياري - فقط لأجل ان وجد لديكم اي ملاحظة للعمل عليها مستقبلاً', max_length=1000, null=True, verbose_name='ملاحظة قصيرة'),
        ),
    ]
