# Generated by Django 3.2.22 on 2023-12-04 06:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0002_auto_20231203_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='detial_en',
            field=tinymce.models.HTMLField(default=' ', max_length=100000, null=True, verbose_name='التفاصيل بالانجليزي'),
        ),
        migrations.AddField(
            model_name='about',
            name='titel_en',
            field=models.CharField(default='', max_length=250, verbose_name='العنوان بالانجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectives',
            name='detial_en',
            field=tinymce.models.HTMLField(blank=True, default=' ', null=True, verbose_name='تفاصيل بالانجليزي'),
        ),
        migrations.AddField(
            model_name='objectives',
            name='titel_en',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان القسم'),
        ),
        migrations.AddField(
            model_name='ourvision',
            name='detial_en',
            field=tinymce.models.HTMLField(blank=True, default=' ', null=True, verbose_name='تفاصيل رؤية الشركة بالانجليزي'),
        ),
        migrations.AddField(
            model_name='ourvision',
            name='titel_en',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان القسم بالانجليزي'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='detial_ar',
            field=tinymce.models.HTMLField(blank=True, default=' ', null=True, verbose_name='تفاصيل بالانجليزي'),
        ),
    ]
