# Generated by Django 3.2.22 on 2023-12-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0003_auto_20231204_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='detial_ar',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='تفاصيل بالانجليزي'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='titel_en',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان القسم انجليزي'),
        ),
    ]
