# Generated by Django 3.2.22 on 2023-12-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0006_remove_objectives_detail_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectives',
            name='detail_ar',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True, verbose_name='تفاصيل بالعربي'),
        ),
    ]
