# Generated by Django 3.2.22 on 2023-12-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0007_objectives_detail_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='detail_ar',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='تفاصيل بالعربي'),
        ),
    ]
