# Generated by Django 3.2.22 on 2023-12-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0008_alter_objectives_detail_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectives',
            name='detail_ar',
        ),
    ]
