# Generated by Django 3.2.22 on 2023-12-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0009_remove_objectives_detail_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='detial_en',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='تفاصيل بالانجليزي'),
        ),
    ]
