# Generated by Django 3.2.22 on 2023-12-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0011_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values',
            old_name='detial_ar',
            new_name='detail_ar',
        ),
        migrations.RenameField(
            model_name='values',
            old_name='detial_en',
            new_name='detail_en',
        ),
        migrations.RenameField(
            model_name='values',
            old_name='titel',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='values',
            old_name='titel_en',
            new_name='title_en',
        ),
    ]
