# Generated by Django 3.2.22 on 2023-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0014_ourstartup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourstartup',
            options={'managed': True, 'verbose_name': 'نشـأة البنك', 'verbose_name_plural': 'نشـأة البنك'},
        ),
        migrations.RemoveField(
            model_name='massegeabout',
            name='detial_ar',
        ),
        migrations.RemoveField(
            model_name='massegeabout',
            name='titel',
        ),
        migrations.AddField(
            model_name='massegeabout',
            name='detail_ar',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='التفاصيل بالعربي'),
        ),
        migrations.AddField(
            model_name='massegeabout',
            name='detail_en',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='التفاصيل بالانجليزي'),
        ),
        migrations.AddField(
            model_name='massegeabout',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='massegeabout',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='العنوان انجليزي'),
        ),
    ]
