# Generated by Django 3.2.22 on 2023-12-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0015_auto_20231216_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourstartup',
            old_name='detial_ar',
            new_name='detail_ar',
        ),
        migrations.RenameField(
            model_name='ourstartup',
            old_name='detial_en',
            new_name='detail_en',
        ),
    ]
