# Generated by Django 3.2.22 on 2023-12-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0016_auto_20231216_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourstartup',
            old_name='titel',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ourstartup',
            old_name='titel_en',
            new_name='title_en',
        ),
    ]
