# Generated by Django 3.2.22 on 2023-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurVision', '0017_auto_20231216_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstartup',
            name='detail_ar',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='تفاصيل النشأة'),
        ),
        migrations.AlterField(
            model_name='ourstartup',
            name='detail_en',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='تفاصيل النشأة بالانجليزي'),
        ),
        migrations.AlterField(
            model_name='ourstartup',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان النشأة'),
        ),
        migrations.AlterField(
            model_name='ourstartup',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان النشأة بالانجليزي'),
        ),
    ]
