# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': True, 'verbose_name': 'العملاء', 'verbose_name_plural': 'العملاء'},
        ),
    ]
