# Generated by Django 3.2.22 on 2023-11-09 10:57

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_at', models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='الاسم انجليزي')),
                ('name_ar', models.CharField(db_index=True, max_length=200, null=True, verbose_name='الاسم عربي')),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='الاسم  أسكي')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_ascii')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='المعرف')),
                ('alternate_names', models.TextField(blank=True, default='', null=True, verbose_name='أسماء بديلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('code2', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('code3', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('continent', models.CharField(choices=[('OC', 'أوقيانوسيا'), ('EU', 'اوروبا'), ('AF', 'افريقيا'), ('NA', 'أمريكا الشمالية'), ('AN', 'القارة القطبية الجنوبية'), ('SA', 'أمريكا الجنوبية'), ('AS', 'اسيا')], db_index=True, max_length=2, verbose_name='القارة')),
                ('tld', models.CharField(blank=True, db_index=True, max_length=5)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='مفتاح التلفون')),
            ],
            options={
                'verbose_name_plural': 'الدول',
                'ordering': ['phone'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_at', models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='الاسم انجليزي')),
                ('name_ar', models.CharField(db_index=True, max_length=200, null=True, verbose_name='الاسم عربي')),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='الاسم  أسكي')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_ascii')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='المعرف')),
                ('alternate_names', models.TextField(blank=True, default='', null=True, verbose_name='أسماء بديلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('display_name_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم العرض عربي')),
                ('display_name', models.CharField(max_length=200, verbose_name='اسم العرض انجليزي')),
                ('geoname_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رمز الاسم الجغرافي')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_regions.country', verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'المحافظة/الولاية',
                'verbose_name_plural': 'المحافظة/الولاية',
                'ordering': ['name_ar'],
                'abstract': False,
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_at', models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='الاسم انجليزي')),
                ('name_ar', models.CharField(db_index=True, max_length=200, null=True, verbose_name='الاسم عربي')),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='الاسم  أسكي')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_ascii')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='المعرف')),
                ('alternate_names', models.TextField(blank=True, default='', null=True, verbose_name='أسماء بديلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('display_name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name', models.CharField(max_length=200)),
                ('geoname_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_regions.region')),
            ],
            options={
                'verbose_name': 'المديرية',
                'verbose_name_plural': 'المديرية',
                'ordering': ['name_ar'],
                'abstract': False,
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Isolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_at', models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('name', models.CharField(db_index=True, max_length=200, null=True, verbose_name='الاسم انجليزي')),
                ('name_ar', models.CharField(db_index=True, max_length=200, null=True, verbose_name='الاسم عربي')),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='الاسم  أسكي')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_ascii')),
                ('geoname_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='المعرف')),
                ('alternate_names', models.TextField(blank=True, default='', null=True, verbose_name='أسماء بديلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('display_name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name', models.CharField(max_length=200)),
                ('geoname_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country_regions.directorate')),
            ],
            options={
                'verbose_name': 'العزلة',
                'verbose_name_plural': 'العزلة',
                'ordering': ['name_ar'],
                'abstract': False,
                'unique_together': {('directorate', 'name')},
            },
        ),
    ]
