# Generated by Django 3.2.22 on 2023-11-09 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_regions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255, null=True, verbose_name='العنوان')),
                ('street', models.CharField(blank=True, default='', max_length=55, verbose_name='الشارع')),
                ('postcode', models.CharField(blank=True, default='', max_length=64, verbose_name='Post/Zip-code')),
                ('map_location', models.URLField(blank=True, help_text='https://www.google.com/maps/@15.3616384,44.2073088,13z?entry=ttu', null=True, verbose_name='رابط الموقع على خرائط جوجل')),
                ('lat', models.FloatField(null=True, verbose_name=' خط العرض')),
                ('long', models.FloatField(null=True, verbose_name=' خط الطول')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='country_regions.region', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'عنوان فروع',
                'verbose_name_plural': 'عناوين الفروع',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SerchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, help_text='اسم الفرع او اسم الشارع او اسم نقطة الخدمة', max_length=64, null=True, verbose_name='ابحث هنا')),
                ('category', models.CharField(blank=True, choices=[('فرع', 'فرع'), ('صراف آلي', 'صراف آلي'), ('وكيل', 'وكيل')], max_length=100, null=True, verbose_name='نوع نقطة الخدمة')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='country_regions.region', verbose_name='region - المدينة')),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='اسم الفرع')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='رقم التلفون  ')),
                ('HORSE', models.CharField(choices=[('24', '24 ساعة'), ('فترتين', 'فترتين'), ('فترة واحده', 'فترة واحده')], max_length=100, null=True, verbose_name='اوقات الدوام')),
                ('from_hourse_firest', models.TimeField(blank=True, null=True, verbose_name='اوقات الدوام')),
                ('to_hourse_firest', models.TimeField(blank=True, null=True, verbose_name='اوقات الدوام')),
                ('from_hourse_scond', models.TimeField(blank=True, null=True, verbose_name='اوقات الدوام')),
                ('to_hourse_scond', models.TimeField(blank=True, null=True, verbose_name='اوقات الدوام')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الأنشاء ')),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ اخر تعديل ')),
                ('category', models.CharField(choices=[('فرع', 'فرع'), ('صراف آلي', 'صراف آلي'), ('وكيل', 'وكيل')], max_length=100, null=True, verbose_name='نوع نقطة الخدمة')),
                ('address1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_address1', to='branches.address', verbose_name=' العنوان 1')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_model_created_by', to=settings.AUTH_USER_MODEL, verbose_name='تم الأنشاء بواسطة ')),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_model_edited_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم التعديل  بواسطة ')),
            ],
            options={
                'verbose_name': 'الفروع و نقاط الخدمة',
                'verbose_name_plural': 'نقاط الخدمة ,الفرع',
                'managed': True,
            },
        ),
    ]
