# Generated by Django 3.2.22 on 2023-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='اسم الفرع بالانجليزي'),
        ),
    ]
