# Generated by Django 3.2.22 on 2023-11-09 11:00

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emile', models.EmailField(error_messages={'required': 'Please enter correct emile. .', 'unique': 'البريد الألكتروني موجود من سابق'}, max_length=254, null=True, unique=True, verbose_name='البريد الألكتروني')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
            ],
            options={
                'verbose_name': 'مشتركين في اخر الاخبار',
                'verbose_name_plural': 'مشتركين في اخر الاخبار',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم تلفون الواتساب')),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='رقم التلفون ')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='إسمك')),
                ('emile', models.EmailField(blank=True, max_length=254, null=True, verbose_name='  البريد الألكتروني')),
                ('Message', models.TextField(max_length=1000, null=True, verbose_name='الرساله')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country_regions.country', verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'اتصل بناء ',
                'verbose_name_plural': 'اتصل بناء',
                'managed': True,
            },
        ),
    ]
