# Generated by Django 3.2.22 on 2023-11-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_dolar', models.IntegerField(null=True, verbose_name=' سعر البيع للدولار')),
                ('buy_dolar', models.IntegerField(null=True, verbose_name=' سعر الشراء للدولار')),
                ('buy_emarat', models.IntegerField(null=True, verbose_name=' سعر الشراء اماراتي')),
                ('sale_emarat', models.IntegerField(null=True, verbose_name=' سعر البيع اماراتي')),
                ('buy_ksa', models.IntegerField(null=True, verbose_name=' سعر الشراء سعودي')),
                ('sale_ksa', models.IntegerField(null=True, verbose_name=' سعر البيع سعودي')),
            ],
            options={
                'verbose_name': 'اسعار الصرف ',
                'verbose_name_plural': ' اسعار الصرف ',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
