# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'managed': True, 'verbose_name': 'اسعار الصرف', 'verbose_name_plural': 'اسعار الصرف'},
        ),
    ]
