# Generated by Django 4.2.7 on 2024-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_exchangerate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='region',
            field=models.CharField(default='عدن', max_length=200, verbose_name='المحافظة'),
        ),
    ]
