# Generated by Django 3.2.22 on 2023-11-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم القسم  ')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
            ],
            options={
                'verbose_name': 'اقسام معرض الأعمال  ',
                'verbose_name_plural': 'قسم معرض الأعمال',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImagesPortfolioNoDetils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default=' ', max_length=250, null=True, verbose_name='عنوان الصورة  ')),
                ('image', models.ImageField(null=True, upload_to='Image/ImagesPortfolioNoDetils/%Y/%m/%d/', verbose_name=' إختيار صورة')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأضافة')),
                ('Date_Update', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': ' معرض الصور  ',
                'verbose_name_plural': ' معرض الصور   ',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='اسم العميل   (إختياري)')),
                ('PhoneNo_one', models.CharField(blank=True, max_length=250, null=True, verbose_name='  رقم  التلفون الأول   (إختياري)')),
                ('PhoneNo_two', models.CharField(blank=True, max_length=250, null=True, verbose_name='  رقم  التلفون الثاني   (إختياري)')),
                ('PhoneNo_whatsapp', models.CharField(blank=True, max_length=250, null=True, verbose_name='  رقم  التلفون واتس أب   (إختياري)')),
                ('PhoneNo_landline', models.CharField(blank=True, max_length=250, null=True, verbose_name='  رقم  الثابت (إختياري)')),
                ('Url_ForProject', models.URLField(blank=True, null=True, verbose_name='  رابط للخدمة ان وجد  ')),
                ('detial_ar', tinymce.models.HTMLField(blank=True, max_length=100000, null=True, verbose_name='التفاصيل  ')),
                ('titel', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان العمل  ')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.category', verbose_name='القسم   ')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='   (إختياري) تم الأنشاء بواسطة ')),
            ],
            options={
                'verbose_name': 'معرض الأعمال',
                'verbose_name_plural': 'معرض الأعمال الشركة معا كتابة التفاصيل',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImagesPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Image/ImagesPortfolio/%Y/%m/%d/', verbose_name=' إختيار صورة')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأضافة')),
                ('Date_Update', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolioapp.portfolio', verbose_name=' المعرض')),
            ],
            options={
                'verbose_name': 'صور معرض اعمال الشركة  ',
                'verbose_name_plural': 'صور اعمال الشركة مع التفاصيل  ',
            },
        ),
    ]
