# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesportfolionodetils',
            options={'verbose_name': 'معرض الصور', 'verbose_name_plural': 'معرض الصور'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='اسم القسم'),
        ),
        migrations.AlterField(
            model_name='imagesportfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='Image/ImagesPortfolio/%Y/%m/%d/', verbose_name='إختيار صورة'),
        ),
        migrations.AlterField(
            model_name='imagesportfolio',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolioapp.portfolio', verbose_name='المعرض'),
        ),
        migrations.AlterField(
            model_name='imagesportfolionodetils',
            name='image',
            field=models.ImageField(null=True, upload_to='Image/ImagesPortfolioNoDetils/%Y/%m/%d/', verbose_name='إختيار صورة'),
        ),
        migrations.AlterField(
            model_name='imagesportfolionodetils',
            name='titel',
            field=models.CharField(default=' ', max_length=250, null=True, verbose_name='عنوان الصورة'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='PhoneNo_landline',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم  الثابت (إختياري)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='PhoneNo_one',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم  التلفون الأول   (إختياري)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='PhoneNo_two',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم  التلفون الثاني   (إختياري)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='PhoneNo_whatsapp',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم  التلفون واتس أب   (إختياري)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='Url_ForProject',
            field=models.URLField(blank=True, null=True, verbose_name='رابط للخدمة ان وجد'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.category', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='(إختياري) تم الأنشاء بواسطة '),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='detial_ar',
            field=tinymce.models.HTMLField(blank=True, max_length=100000, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='titel',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان العمل'),
        ),
    ]
