# Generated by Django 3.2.22 on 2023-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsence',
            options={'managed': True, 'verbose_name': 'الأعلانات', 'verbose_name_plural': 'الأعلانات'},
        ),
        migrations.AlterField(
            model_name='adsenceheder',
            name='Description_AR',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='الوصف بالعربي'),
        ),
        migrations.AlterField(
            model_name='adsenceheder',
            name='Description_EN',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='الوصف بالانجليزي'),
        ),
    ]
