# Generated by Django 3.2.22 on 2023-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsense', '0002_auto_20231203_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsenceheder',
            name='image_en',
            field=models.ImageField(null=True, upload_to='Image/Adsence/AdsenceHeder/%Y/%m/%d/%H/%M/%S', verbose_name='صورة الاعلان انجليزي'),
        ),
    ]
