# Generated by Django 3.2.22 on 2023-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.IntegerField(max_length=200, verbose_name='نوع التقرير')),
                ('thumbnail_name', models.CharField(max_length=200, verbose_name='الصورة المصغرة')),
                ('filename', models.CharField(max_length=200, verbose_name='اسم الملف')),
            ],
            options={
                'verbose_name': 'التقرير',
                'verbose_name_plural': 'التقارير',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفيديو')),
                ('source_type', models.IntegerField(max_length=200, verbose_name='مصدر الفيديو')),
                ('url', models.CharField(max_length=200, verbose_name='رابط الفيديو')),
                ('path', models.CharField(max_length=200, verbose_name='مسار الفيديو')),
            ],
            options={
                'verbose_name': 'الفيديو',
                'verbose_name_plural': 'مكتبة الفيديوهات',
                'managed': True,
            },
        ),
    ]
