# Generated by Django 3.2.22 on 2023-11-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('file', 'ملف'), ('url', 'رابط')], max_length=200, verbose_name='مصدر الفيديو'),
        ),
    ]
