# Generated by Django 3.2.22 on 2023-11-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_library', '0002_alter_video_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('yearly', 'تقرير سنوي'), ('finance', 'تقرير سنوي')], max_length=200, verbose_name='نوع التقرير'),
        ),
    ]
