# Generated by Django 3.2.22 on 2023-11-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_library', '0003_alter_report_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.FileField(default=1, max_length=200, upload_to='', verbose_name='ملف الفيديو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='filename',
            field=models.FileField(max_length=200, upload_to='', verbose_name='ملف التقرير'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('yearly', 'تقرير سنوي'), ('finance', 'تقرير مالي')], max_length=200, verbose_name='نوع التقرير'),
        ),
        migrations.AlterField(
            model_name='report',
            name='thumbnail_name',
            field=models.FileField(max_length=200, upload_to='', verbose_name='صورة التقرير'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='رابط الفيديو'),
        ),
    ]
