# Generated by Django 3.2.22 on 2023-11-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_library', '0004_auto_20231121_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='mime_type',
            field=models.CharField(default=1, max_length=200, verbose_name='نوع الفيديو'),
            preserve_default=False,
        ),
    ]
