# Generated by Django 3.2.22 on 2023-11-09 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250, null=True, verbose_name='عنوان القسم  ')),
                ('short_titel', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='جملة قصيرة اسفل العنوان')),
                ('detial_ar', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='تفاصيل')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
                ('image', models.ImageField(null=True, upload_to='Image/SectionPage/%Y/%m/%d/', verbose_name=' إختيار صورة')),
                ('view', models.CharField(choices=[('الرئيسية', 'الصفحة الرئيسية'), ('منفصل', 'صفحة منفصل')], max_length=100, null=True, verbose_name='صفحة عرض القسم')),
                ('number_rows', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], help_text='عدد الصفوف العناصر في عرض الشاشة', max_length=100, null=True, verbose_name='عدد الصفوف')),
                ('is_hidden', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا  من العرض بالموقع بحال تم تحديده', verbose_name='مخفي')),
                ('is_deleted', models.BooleanField(default=False, help_text='سيتم اخفاء هذا الرئي من العرض بالموقع بحال تم تحديده وسيعتبر انه قد تم حذفه  ', verbose_name='محذوف ')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الحذف ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأنشاء ')),
                ('edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ اخر تعديل ')),
                ('sort_no', models.IntegerField(blank=True, help_text=' اختياري - يتم ترتيب ظهور الأراء على حسب الرقم هذا ان وجد', null=True, verbose_name='رقم الترتيب ')),
                ('short_note', models.CharField(blank=True, default=' ', help_text=' اختياري - فقط لأجل ان وجد لديكم اي ملاحظة للعمل عليها مستقبلاً', max_length=1000, null=True, verbose_name='ملاحظة قصيرة')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SectionPage_created_by', to=settings.AUTH_USER_MODEL, verbose_name='تم الأنشاء بواسطة ')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SectionPage_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم الحذف  بواسطة ')),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SectionPage_edited_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم التعديل  بواسطة ')),
            ],
            options={
                'verbose_name': 'الاقسام والصفحات',
                'verbose_name_plural': 'الاقسام والصفحات',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectionPageProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250, null=True, verbose_name='عنوان الغاية  ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image/SectionPage/%Y/%m/%d/', verbose_name=' إختيار صورة')),
                ('detial_ar', tinymce.models.HTMLField(blank=True, null=True, verbose_name='التفاصيل')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأضافة')),
                ('Date_Update', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('is_hidden', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا  من العرض بالموقع بحال تم تحديده', verbose_name='مخفي')),
                ('is_deleted', models.BooleanField(default=False, help_text='سيتم اخفاء هذا الرئي من العرض بالموقع بحال تم تحديده وسيعتبر انه قد تم حذفه  ', verbose_name='محذوف ')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الحذف ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأنشاء ')),
                ('edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ اخر تعديل ')),
                ('sort_no', models.IntegerField(blank=True, help_text=' اختياري - يتم ترتيب ظهور الأراء على حسب الرقم هذا ان وجد', null=True, verbose_name='رقم الترتيب ')),
                ('short_note', models.CharField(blank=True, default=' ', help_text=' اختياري - فقط لأجل ان وجد لديكم اي ملاحظة للعمل عليها مستقبلاً', max_length=1000, null=True, verbose_name='ملاحظة قصيرة')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SectionPageProperty_created_by', to=settings.AUTH_USER_MODEL, verbose_name='تم الأنشاء بواسطة ')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SectionPageProperty_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم الحذف  بواسطة ')),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SectionPageProperty_edited_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم التعديل  بواسطة ')),
                ('our_advantage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='our_dvantages_property', to='sectionpage.sectionpage', verbose_name=' القسم')),
            ],
            options={
                'verbose_name': 'محتوى فرعي للقسم',
                'verbose_name_plural': 'محتوى فرعي للقسم',
                'managed': True,
            },
        ),
    ]
