# Generated by Django 3.2.22 on 2023-12-04 06:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sectionpage', '0002_auto_20231203_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='detial_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='تفاصيل بالانجليزي'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='short_titel_en',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='جملة قصيرة اسفل العنوان بالانجليزي'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='titel_en',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان القسم بالانجليزي'),
        ),
    ]
