# Generated by Django 3.2.22 on 2023-11-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_auto_20231119_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guaranteetype',
            options={'managed': True, 'verbose_name': 'نوع  الضمانة', 'verbose_name_plural': 'نوع الضمانات'},
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='')),
                ('mobile_number', models.CharField(max_length=200, verbose_name='')),
                ('city_name', models.CharField(max_length=200, verbose_name='')),
                ('street_name', models.CharField(max_length=200, verbose_name='')),
                ('nearest_known_place', models.CharField(max_length=200, verbose_name='')),
                ('project_created_at', models.DateTimeField(max_length=20, verbose_name='')),
                ('current_capital', models.IntegerField(max_length=200, verbose_name='')),
                ('loan_purpose', models.CharField(max_length=200, verbose_name='')),
                ('required_amount', models.IntegerField(max_length=200, verbose_name='')),
                ('loan_months', models.IntegerField(max_length=200, verbose_name='')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loan_app.activitytype')),
                ('guarantee_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loan_app.guaranteetype')),
            ],
            options={
                'verbose_name': 'طلب التمويل',
                'verbose_name_plural': 'طلبات التمويل',
                'managed': True,
            },
        ),
    ]
