# Generated by Django 3.2.22 on 2023-11-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_auto_20231119_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_installment',
            field=models.IntegerField(default=1, max_length=200, verbose_name='القسط الشهري'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loan_app.activitytype', verbose_name='نوع النشاط'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='city_name',
            field=models.CharField(max_length=200, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='current_capital',
            field=models.IntegerField(max_length=200, verbose_name='رأس مال المشروع حالياً'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='guarantee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loan_app.guaranteetype', verbose_name='نوع الضمانة'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_months',
            field=models.IntegerField(max_length=200, verbose_name='مدة التمويل بالأشهر'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_purpose',
            field=models.CharField(max_length=200, verbose_name='غرض التمويل'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='mobile_number',
            field=models.CharField(max_length=200, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='nearest_known_place',
            field=models.CharField(max_length=200, verbose_name='أقرب معلم بارز'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='project_created_at',
            field=models.DateTimeField(max_length=20, verbose_name='عمر المشروع(تاريخ التأسيس)'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='required_amount',
            field=models.IntegerField(max_length=200, verbose_name='مبلغ التمويل المطلوب'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='street_name',
            field=models.CharField(max_length=200, verbose_name='الحي/الشارع'),
        ),
    ]
