# Generated by Django 3.2.22 on 2023-11-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0005_loanapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='project_created_at',
            field=models.DateField(max_length=20, verbose_name='عمر المشروع(تاريخ التأسيس)'),
        ),
    ]
