# Generated by Django 3.2.22 on 2023-11-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_alter_loanapplication_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='project_created_at',
            field=models.DateField(blank=True, null=True, verbose_name='عمر المشروع(تاريخ التأسيس)'),
        ),
    ]
