# Generated by Django 3.2.22 on 2023-11-09 11:03

import Testimonials.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text=" سيتم عرضها بالموقع مثال '  ابراهيم شاهر'    ", max_length=250, verbose_name='الأسم الكامل (سيتم عرضها بالموقع)')),
                ('adjective', models.CharField(default=' ', help_text=" سيتم عرضها بالموقع مثال 'الرئيس التنفيذي لشركة رواد'    ", max_length=250, null=True, verbose_name=' الصفة او المهنة ')),
                ('evaluation_number', models.PositiveIntegerField(default=5, error_messages={'invalid_choice': 'اختيار من 1 الى 5'}, help_text='(سيتم عرضها بالموقع على هيئة نجوم)', null=True, verbose_name=' رقم تقييم العميل للشركة   ')),
                ('detial_ar', tinymce.models.HTMLField(default='', null=True, verbose_name='الشهادة او التوصيات او الرأْي (سيتم عرضها بالموقع)')),
                ('is_hidden', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا  من العرض بالموقع بحال تم تحديده', verbose_name='مخفي')),
                ('is_deleted', models.BooleanField(default=False, help_text='سيتم اخفاء هذا الرئي من العرض بالموقع بحال تم تحديده وسيعتبر انه قد تم حذفه  ', verbose_name='محذوف ')),
                ('facebook', models.URLField(blank=True, null=True, validators=[Testimonials.models.validate_facebook], verbose_name='رابط حساب الفيسبوك (إن وجد - اختياري - لن يتم عرضه في الموقع ) ')),
                ('twitter', models.URLField(blank=True, error_messages={'invalid': '  رابط تويتر  فقط '}, help_text='(إن وجد - اختياري - لن يتم عرضه في الموقع )', null=True, validators=[Testimonials.models.validate_twitter], verbose_name='رابط حساب تويتر ')),
                ('instagram', models.URLField(blank=True, error_messages={'invalid': '  رابط انستجرا م  فقط '}, help_text='(إن وجد - اختياري - لن يتم عرضه في الموقع )', null=True, validators=[Testimonials.models.validate_instagram], verbose_name='رابط حساب انستجرام ')),
                ('linkedin', models.URLField(blank=True, error_messages={'invalid': '  رابط لنكدإن  فقط '}, help_text='(إن وجد - اختياري - لن يتم عرضه في الموقع )', null=True, validators=[Testimonials.models.validate_linkedin], verbose_name='رابط حساب لنكدإن ')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الحذف ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الأنشاء ')),
                ('edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ اخر تعديل ')),
                ('sort_no', models.IntegerField(blank=True, help_text='(  اختياري - يتم ترتيب ظهور الأراء على حسب الرقم هذا ان وجد)', null=True, verbose_name='رقم الترتيب ')),
                ('short_note', models.CharField(blank=True, default=' ', help_text=' اختياري - فقط لأجل ان وجد لديكم اي ملاحظة للعمل عليها مستقبلاً', max_length=200, null=True, verbose_name='ملاحظة قصيرة (إن وجد - لن يتم عرضه في الموقع )')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الأنشاء بواسطة ')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Testimonials_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم الحذف  بواسطة ')),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Testimonials_edited_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم التعديل  بواسطة ')),
            ],
            options={
                'verbose_name': 'آراء العملاء',
                'verbose_name_plural': 'آراء العملاء',
                'managed': True,
            },
        ),
    ]
