# Generated by Django 3.2.22 on 2023-12-03 19:42

import Testimonials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='instagram',
            field=models.URLField(blank=True, error_messages={'invalid': 'رابط انستجرا م  فقط '}, help_text='(إن وجد - اختياري - لن يتم عرضه في الموقع )', null=True, validators=[Testimonials.models.validate_instagram], verbose_name='رابط حساب انستجرام '),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='linkedin',
            field=models.URLField(blank=True, error_messages={'invalid': 'رابط لنكدإن  فقط '}, help_text='(إن وجد - اختياري - لن يتم عرضه في الموقع )', null=True, validators=[Testimonials.models.validate_linkedin], verbose_name='رابط حساب لنكدإن '),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='twitter',
            field=models.URLField(blank=True, error_messages={'invalid': 'رابط تويتر  فقط'}, help_text='(إن وجد - اختياري - لن يتم عرضه في الموقع )', null=True, validators=[Testimonials.models.validate_twitter], verbose_name='رابط حساب تويتر '),
        ),
    ]
