# Generated by Django 3.2.22 on 2023-11-09 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import settingapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.CharField(default=' جميع الحقوق محفوظة © لـ بنك الإنماء للتمويل الأصغر الإسلامي 2023', max_length=300, null=True)),
                ('name_website_short', models.CharField(blank=True, default='بنك الإنماء', max_length=20, null=True, verbose_name='اسم website مختصر')),
                ('name_website', models.CharField(blank=True, default=' بنك الإنماء للتمويل الأصغر الإسلامي ', max_length=50, null=True, verbose_name='اسم website')),
                ('facebook', models.URLField(blank=True, help_text='https://facebook.com', null=True, validators=[settingapp.models.validate_hostname], verbose_name='رابط حساب الفيسبوك إن وجد ')),
                ('telegram', models.URLField(blank=True, help_text='https://t.me/', null=True, validators=[settingapp.models.validate_hostname], verbose_name='رابط تلجرام إن وجد ')),
                ('twitter', models.URLField(blank=True, help_text='https://twitter.com', null=True, validators=[settingapp.models.validate_hostname], verbose_name='رابط حساب تويتر او منصة اكس إن وجد ')),
                ('instagram', models.URLField(blank=True, help_text='https://instagram.com', null=True, validators=[settingapp.models.validate_hostname], verbose_name='رابط حساب انستجرام إن وجد ')),
                ('linkedin', models.URLField(blank=True, null=True, validators=[settingapp.models.validate_hostname], verbose_name='رابط حساب لنكدإن  إن وجد ')),
                ('youtube', models.URLField(blank=True, help_text='https://youtube.com', null=True, validators=[settingapp.models.validate_hostname], verbose_name='رابط قناة اليوتيوب ')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='https://api.whatsapp.com/send/?phone=phone_number_whatsapp', max_length=20, null=True, region=None, verbose_name='رقم تلفون الواتساب')),
                ('phone_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='هاتف 1')),
                ('phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='هاتف 2')),
                ('fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='فاكس')),
                ('free_phone_numbar', models.CharField(blank=True, max_length=250, null=True, verbose_name='الرقم المجاني')),
                ('emile', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('mail_box', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الصندوق البريدي')),
                ('Date_Update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل ')),
                ('Date_Added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافة ')),
                ('is_hidden_branche', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم الفروع')),
                ('is_hidden_contact', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم اتصل بنا')),
                ('is_hidden_about', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم نبذه عنا')),
                ('is_hidden_button_action', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء action  ')),
                ('is_hidden_client', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم  العملاء')),
                ('is_hidden_galary', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم معرض الصور')),
                ('is_hidden_teams', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم فريق العمل')),
                ('is_hidden_partner', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم شركائنا')),
                ('is_hidden_ournewsletter', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم اشترك باخر الاخبار')),
                ('is_hidden_imagesportfolionodetils', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم معرض الــصــور')),
                ('is_hidden_ourmarch', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم مسيرتنــــا')),
                ('is_hidden_sectio_page_all', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم الاقسام والصفحات')),
                ('is_hidden_sectio_page_in_home_only', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم الاقسام والصفحات من الشاشة الرئسية فقط')),
                ('is_hidden_ourmission', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم مهمتنــــا')),
                ('is_hidden_bank_applications', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم تطبيقات البنك')),
                ('is_hidden_adsence_header', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم الاعلانات المتحركة في اعلا الصفحه')),
                ('is_hidden_last_news', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم اخر الاخبار في الشاشة الرئيسية ')),
                ('is_hidden_footer', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name="اخفاء  اسفل الصفحة 'footer' بشكل كامل  ")),
                ('is_hidden_faq', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم الأسئلة الشائعة')),
                ('is_hidden_currencies', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء اسعار العملات ')),
                ('is_hidden_logo_ainmation', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم الشعار اعلا اسفل الصفحة ')),
                ('is_hidden_images_portfolio_no_detils', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم معرض الصور ')),
                ('is_hidden_services', models.BooleanField(default=False, help_text=' سيتم اخفاء هذا القسم  من العرض بالموقع بحال تم تحديده', verbose_name='اخفاء قسم خدمات ')),
                ('is_deleted', models.BooleanField(default=False, help_text='سيتم اخفاء هذا الرئي من العرض بالموقع بحال تم تحديده وسيعتبر انه قد تم حذفه  ', verbose_name='محذوف ')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الحذف ')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ الأنشاء ')),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاريخ اخر تعديل ')),
                ('short_note', models.CharField(blank=True, default=' ', help_text=' اختياري - فقط لأجل ان وجد لديكم اي ملاحظة للعمل عليها مستقبلاً', max_length=1000, null=True, verbose_name='ملاحظة قصيرة')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_model_created_by', to=settings.AUTH_USER_MODEL, verbose_name='تم الأنشاء بواسطة ')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_model_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم الحذف  بواسطة ')),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_model_edited_by', to=settings.AUTH_USER_MODEL, verbose_name=' تم التعديل  بواسطة ')),
            ],
            options={
                'verbose_name': 'الاعــــدادات',
                'verbose_name_plural': 'الاعـــدادات',
                'managed': True,
            },
        ),
    ]
