# Generated by Django 3.2.22 on 2023-12-04 12:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('FrequentlyAskedQuestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestions',
            name='answer_en',
            field=tinymce.models.HTMLField(default=' ', max_length=100000, null=True, verbose_name='الأجابة بالانجليزي'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestions',
            name='question_en',
            field=models.CharField(default='', max_length=250, verbose_name='السؤال بالانجليزي'),
            preserve_default=False,
        ),
    ]
